apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: youtube-main
spec:
  replicas: 4
  selector:
    matchLabels:
      app: youtube-main
  template:
    metadata:
      labels:
        app: youtube-main
    spec:
      containers:
        - name: youtube-main
          image: uniyalrachna/youtube-main:v1
          ports:
            - containerPort: 80
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {duration: 5}
      - setWeight: 50
      - pause: {duration: 5}
      - setWeight: 100